### ISSUE TITLE
Always return the primary monitor with multiple monitors.

### ISSUE THREAD

**Issue by MicroscopyLab** [cafarm/matlab-glfw#9]
The follow code cannot return the correct monitor name. The total number of monitors is correct, but not the true pointer. 
```
glfwInit();
monitors = glfwGetMonitors();
for mon=monitors
      glfwGetMonitorName(mon)
end
```

**Comment by cafarm** [comment]
I was able to reproduce this issue on my machine as well. Will look into it.
